name: Continuous Deployment

on:
  push:
    branches:
      - main

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  ci:
    uses: ./.github/workflows/CI.yml
    secrets: inherit

  cd:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: 'https://registry.npmjs.org'

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: dist

      - name: Publish
        run: npm publish --access public
