name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: 'https://registry.npmjs.org'

      - name: Use pnpm 8.x
        uses: pnpm/action-setup@v2
        with:
          version: 8.x
          run_install: |
            - recursive: true
              args: [--frozen-lockfile]

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test

      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./dist
