name: Upload Docs to S3

on:
  push:
    branches:
      - main

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: 'https://registry.npmjs.org'

      - uses: actions/checkout@master
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install --immutable

      - name: Generate docs
        run: yarn docs:generate

      - uses: shallwefootball/s3-upload-action@master
        name: Upload S3
        id: S3
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: 'use-defi-docs'
          source_dir: 'docs'
          destination_dir: ''
