name: Upload Docs to S3

on:
  push:
    branches:
      - main

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: 'https://registry.npmjs.org'

      - name: Use pnpm 8.x
        uses: pnpm/action-setup@v2
        with:
          version: 8.x
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --ignore-scripts]

      - name: Publish to npm
        run: npm publish
